export const indianStatesArray = [
	{
		name: "Andhra Pradesh",
		type: "State",
		latitude: 15.9129,
		longitude: 79.74,
		capital: [
			{
				name: "Visakhapatnam (proposed executive capital)",
				latitude: 17.6868,
				longitude: 83.2185,
			},
			{
				name: "Amaravati (legislative capital)",
				latitude: 16.5417,
				longitude: 80.515,
			},
			{
				name: "Kurnool (judicial capital)",
				latitude: 15.8281,
				longitude: 78.0373,
			},
		],
		largestCity: {
			name: "Visakhapatnam",
			latitude: 17.6868,
			longitude: 83.2185,
		},
		region: "South",
		population: 49577103,
		area: 162975,
		officialLanguages: ["Telugu"],
		formationDate: "1 October 1953; 1 November 1956",
		majorCities: [
			{
				name: "Visakhapatnam",
				latitude: 17.6868,
				longitude: 83.2185,
			},
			{
				name: "Vijayawada",
				latitude: 16.5062,
				longitude: 80.648,
			},
			{
				name: "Guntur",
				latitude: 16.3067,
				longitude: 80.4365,
			},
			{
				name: "Nellore",
				latitude: 14.4426,
				longitude: 79.9865,
			},
			{
				name: "Kurnool",
				latitude: 15.8281,
				longitude: 78.0373,
			},
		],
		districts: [
			"Srikakulam",
			"Vizianagaram",
			"Visakhapatnam",
			"Alluri Sitarama Raju",
			"Anakapalli",
			"Kakinada",
			"East Godavari",
			"Konaseema",
			"West Godavari",
			"Krishna",
			"NTR",
			"Guntur",
			"Bapatla",
			"Palnadu",
			"Prakasam",
			"SPSR Nellore",
			"Kurnool",
			"Nandyal",
			"Anantapur",
			"Sri Sathya Sai",
			"YSR",
			"Annamayya",
			"Chittoor",
			"Tirupati",
		],
	},
	{
		name: "Arunachal Pradesh",
		type: "State",
		latitude: 28.217,
		longitude: 94.7278,
		capital: {
			name: "Itanagar",
			latitude: 27.0844,
			longitude: 93.6053,
		},
		largestCity: {
			name: "Itanagar",
			latitude: 27.0844,
			longitude: 93.6053,
		},
		region: "Northeast",
		population: 1383727,
		area: 83743,
		officialLanguages: ["English"],
		formationDate: "20 February 1987",
		majorCities: [
			{
				name: "Itanagar",
				latitude: 27.0844,
				longitude: 93.6053,
			},
			{
				name: "Naharlagun",
				latitude: 27.1042,
				longitude: 93.6952,
			},
			{
				name: "Pasighat",
				latitude: 28.0663,
				longitude: 95.3268,
			},
			{
				name: "Tawang",
				latitude: 27.5864,
				longitude: 91.859,
			},
		],
		districts: [
			"Tawang",
			"West Kameng",
			"East Kameng",
			"Pakke Kessang",
			"Papum Pare",
			"Itanagar Capital Complex",
			"Kurung Kumey",
			"Kra Daadi",
			"Lower Subansiri",
			"Kamle",
			"Upper Subansiri",
			"West Siang",
			"Shi Yomi",
			"East Siang",
			"Siang",
			"Lower Siang",
			"Upper Siang",
			"Lower Dibang Valley",
			"Dibang Valley",
			"Anjaw",
			"Lohit",
			"Namsai",
			"Changlang",
			"Tirap",
			"Longding",
		],
	},
	{
		name: "Assam",
		type: "State",
		latitude: 26.2006,
		longitude: 92.9376,
		capital: {
			name: "Dispur",
			latitude: 26.1411,
			longitude: 91.7904,
		},
		largestCity: {
			name: "Guwahati",
			latitude: 26.1445,
			longitude: 91.7362,
		},
		region: "Northeast",
		population: 35607039,
		area: 78438,
		officialLanguages: ["Assamese", "Bodo", "Bengali (Barak Valley)"],
		formationDate: "26 January 1950",
		majorCities: [
			{
				name: "Guwahati",
				latitude: 26.1445,
				longitude: 91.7362,
			},
			{
				name: "Silchar",
				latitude: 24.8273,
				longitude: 92.7979,
			},
			{
				name: "Dibrugarh",
				latitude: 27.4728,
				longitude: 94.911,
			},
			{
				name: "Jorhat",
				latitude: 26.7575,
				longitude: 94.2037,
			},
			{
				name: "Nagaon",
				latitude: 26.3494,
				longitude: 92.6846,
			},
		],
		districts: [
			"Bajali",
			"Baksa",
			"Barpeta",
			"Biswanath",
			"Bongaigaon",
			"Cachar",
			"Charaideo",
			"Chirang",
			"Darrang",
			"Dhemaji",
			"Dhubri",
			"Dibrugarh",
			"Goalpara",
			"Golaghat",
			"Hailakandi",
			"Hojai",
			"Jorhat",
			"Kamrup Metropolitan",
			"Kamrup",
			"Karbi Anglong",
			"Karimganj",
			"Kokrajhar",
			"Lakhimpur",
			"Majuli",
			"Morigaon",
			"Nagaon",
			"Nalbari",
			"Dima Hasao (North Cachar Hills)",
			"Sivasagar",
			"Sonitpur",
			"South Salmara-Mankachar",
			"Tinsukia",
			"Udalguri",
			"West Karbi Anglong",
		],
	},
	{
		name: "Bihar",
		type: "State",
		latitude: 25.0961,
		longitude: 85.3131,
		capital: {
			name: "Patna",
			latitude: 25.5941,
			longitude: 85.1376,
		},
		largestCity: {
			name: "Patna",
			latitude: 25.5941,
			longitude: 85.1376,
		},
		region: "East",
		population: 124799926,
		area: 94163,
		officialLanguages: ["Hindi", "Urdu"],
		formationDate: "22 March 1912; 26 January 1950 (state)",
		majorCities: [
			{
				name: "Patna",
				latitude: 25.5941,
				longitude: 85.1376,
			},
			{
				name: "Gaya",
				latitude: 24.7955,
				longitude: 85.0039,
			},
			{
				name: "Bhagalpur",
				latitude: 25.2425,
				longitude: 86.9842,
			},
			{
				name: "Muzaffarpur",
				latitude: 26.1209,
				longitude: 85.3647,
			},
			{
				name: "Purnia",
				latitude: 25.7771,
				longitude: 87.4753,
			},
		],
		districts: [
			"Araria",
			"Arwal",
			"Aurangabad",
			"Banka",
			"Begusarai",
			"Bhagalpur",
			"Bhojpur",
			"Buxar",
			"Darbhanga",
			"East Champaran (Motihari)",
			"Gaya",
			"Gopalganj",
			"Jamui",
			"Jehanabad",
			"Kaimur (Bhabua)",
			"Katihar",
			"Khagaria",
			"Kishanganj",
			"Lakhisarai",
			"Madhepura",
			"Madhubani",
			"Munger",
			"Muzaffarpur",
			"Nalanda",
			"Nawada",
			"Patna",
			"Purnia",
			"Rohtas",
			"Saharsa",
			"Samastipur",
			"Saran",
			"Sheikhpura",
			"Sheohar",
			"Sitamarhi",
			"Siwan",
			"Supaul",
			"Vaishali",
			"West Champaran (Bettiah)",
		],
	},
	{
		name: "Chhattisgarh",
		type: "State",
		latitude: 21.2787,
		longitude: 81.8661,
		capital: {
			name: "Raipur",
			latitude: 21.2514,
			longitude: 81.6296,
		},
		largestCity: {
			name: "Raipur",
			latitude: 21.2514,
			longitude: 81.6296,
		},
		region: "Central",
		population: 29436231,
		area: 135192,
		officialLanguages: ["Hindi", "Chhattisgarhi"],
		formationDate: "1 November 2000",
		majorCities: [
			{
				name: "Raipur",
				latitude: 21.2514,
				longitude: 81.6296,
			},
			{
				name: "Bhilai",
				latitude: 21.1938,
				longitude: 81.3509,
			},
			{
				name: "Bilaspur",
				latitude: 22.0797,
				longitude: 82.1391,
			},
			{
				name: "Durg",
				latitude: 21.1904,
				longitude: 81.2849,
			},
			{
				name: "Korba",
				latitude: 22.3592,
				longitude: 82.7501,
			},
		],
		districts: [
			"Balod",
			"Baloda Bazar",
			"Balrampur",
			"Bastar",
			"Bemetara",
			"Bijapur",
			"Bilaspur",
			"Dantewada (South Bastar)",
			"Dhamtari",
			"Durg",
			"Gariaband",
			"Gaurela-Pendra-Marwahi",
			"Janjgir-Champa",
			"Jashpur",
			"Kabirdham (Kawardha)",
			"Kanker (North Bastar)",
			"Kondagaon",
			"Korba",
			"Koriya",
			"Mahasamund",
			"Mungeli",
			"Narayanpur",
			"Raigarh",
			"Raipur",
			"Rajnandgaon",
			"Sukma",
			"Surajpur",
			"Surguja",
		],
	},
	{
		name: "Goa",
		type: "State",
		latitude: 15.2993,
		longitude: 74.124,
		capital: {
			name: "Panaji",
			latitude: 15.4909,
			longitude: 73.8278,
		},
		largestCity: {
			name: "Vasco da Gama",
			latitude: 15.3969,
			longitude: 73.8154,
		},
		region: "West",
		population: 1458545,
		area: 3702,
		officialLanguages: ["Konkani"],
		formationDate: "30 May 1987",
		majorCities: [
			{
				name: "Panaji",
				latitude: 15.4909,
				longitude: 73.8278,
			},
			{
				name: "Vasco da Gama",
				latitude: 15.3969,
				longitude: 73.8154,
			},
			{
				name: "Margao",
				latitude: 15.2832,
				longitude: 73.986,
			},
			{
				name: "Mapusa",
				latitude: 15.591,
				longitude: 73.8085,
			},
		],
		districts: ["North Goa", "South Goa"],
	},
	{
		name: "Gujarat",
		type: "State",
		latitude: 22.2587,
		longitude: 71.1924,
		capital: {
			name: "Gandhinagar",
			latitude: 23.2156,
			longitude: 72.6369,
		},
		largestCity: {
			name: "Ahmedabad",
			latitude: 23.0225,
			longitude: 72.5714,
		},
		region: "West",
		population: 63872399,
		area: 196024,
		officialLanguages: ["Gujarati"],
		formationDate: "1 May 1960",
		majorCities: [
			{
				name: "Ahmedabad",
				latitude: 23.0225,
				longitude: 72.5714,
			},
			{
				name: "Surat",
				latitude: 21.1702,
				longitude: 72.8311,
			},
			{
				name: "Vadodara",
				latitude: 22.3072,
				longitude: 73.1812,
			},
			{
				name: "Rajkot",
				latitude: 22.3039,
				longitude: 70.8022,
			},
			{
				name: "Bhavnagar",
				latitude: 21.7645,
				longitude: 72.1519,
			},
		],
		districts: [
			"Ahmedabad",
			"Amreli",
			"Anand",
			"Aravalli",
			"Banaskantha",
			"Bharuch",
			"Bhavnagar",
			"Botad",
			"Chhota Udaipur",
			"Dahod",
			"Dang",
			"Devbhoomi Dwarka",
			"Gandhinagar",
			"Gir Somnath",
			"Jamnagar",
			"Junagadh",
			"Kheda",
			"Kutch",
			"Mahisagar",
			"Mehsana",
			"Morbi",
			"Narmada",
			"Navsari",
			"Panchmahal",
			"Patan",
			"Porbandar",
			"Rajkot",
			"Sabarkantha",
			"Surat",
			"Surendranagar",
			"Tapi",
			"Vadodara",
			"Valsad",
		],
	},
	{
		name: "Haryana",
		type: "State",
		latitude: 29.0588,
		longitude: 76.0856,
		capital: {
			name: "Chandigarh",
			latitude: 30.7333,
			longitude: 76.7794,
		},
		largestCity: {
			name: "Faridabad",
			latitude: 28.4089,
			longitude: 77.3178,
		},
		region: "North",
		population: 25351462,
		area: 44212,
		officialLanguages: ["Hindi", "Punjabi (additional)"],
		formationDate: "1 November 1966",
		majorCities: [
			{
				name: "Faridabad",
				latitude: 28.4089,
				longitude: 77.3178,
			},
			{
				name: "Gurugram",
				latitude: 28.4595,
				longitude: 77.0266,
			},
			{
				name: "Panipat",
				latitude: 29.3909,
				longitude: 76.9635,
			},
			{
				name: "Ambala",
				latitude: 30.3782,
				longitude: 76.7767,
			},
			{
				name: "Yamunanagar",
				latitude: 30.129,
				longitude: 77.267,
			},
		],
		districts: [
			"Ambala",
			"Bhiwani",
			"Charkhi Dadri",
			"Faridabad",
			"Fatehabad",
			"Gurugram",
			"Hisar",
			"Jhajjar",
			"Jind",
			"Kaithal",
			"Karnal",
			"Kurukshetra",
			"Mahendragarh",
			"Nuh",
			"Palwal",
			"Panchkula",
			"Panipat",
			"Rewari",
			"Rohtak",
			"Sirsa",
			"Sonipat",
			"Yamunanagar",
		],
	},
	{
		name: "Himachal Pradesh",
		type: "State",
		latitude: 31.1048,
		longitude: 77.1734,
		capital: [
			{
				name: "Shimla (summer)",
				latitude: 31.1048,
				longitude: 77.1734,
			},
			{
				name: "Dharamshala (winter)",
				latitude: 32.219,
				longitude: 76.3234,
			},
		],
		largestCity: {
			name: "Shimla",
			latitude: 31.1048,
			longitude: 77.1734,
		},
		region: "North",
		population: 7300000,
		area: 55673,
		officialLanguages: ["Hindi"],
		formationDate: "25 January 1971",
		majorCities: [
			{
				name: "Shimla",
				latitude: 31.1048,
				longitude: 77.1734,
			},
			{
				name: "Dharamshala",
				latitude: 32.219,
				longitude: 76.3234,
			},
			{
				name: "Kullu",
				latitude: 31.9579,
				longitude: 77.1095,
			},
			{
				name: "Mandi",
				latitude: 31.7096,
				longitude: 76.9326,
			},
			{
				name: "Solan",
				latitude: 30.9205,
				longitude: 77.1227,
			},
		],
		districts: [
			"Bilaspur",
			"Chamba",
			"Hamirpur",
			"Kangra",
			"Kinnaur",
			"Kullu",
			"Lahaul and Spiti",
			"Mandi",
			"Shimla",
			"Sirmaur",
			"Solan",
			"Una",
		],
	},
	{
		name: "Jharkhand",
		type: "State",
		latitude: 23.6102,
		longitude: 85.2799,
		capital: {
			name: "Ranchi",
			latitude: 23.3441,
			longitude: 85.3096,
		},
		largestCity: {
			name: "Jamshedpur",
			latitude: 22.8046,
			longitude: 86.2029,
		},
		region: "East",
		population: 32988134,
		area: 79716,
		officialLanguages: ["Hindi"],
		formationDate: "15 November 2000",
		majorCities: [
			{
				name: "Jamshedpur",
				latitude: 22.8046,
				longitude: 86.2029,
			},
			{
				name: "Dhanbad",
				latitude: 23.7957,
				longitude: 86.4304,
			},
			{
				name: "Ranchi",
				latitude: 23.3441,
				longitude: 85.3096,
			},
			{
				name: "Bokaro",
				latitude: 23.6693,
				longitude: 86.1511,
			},
			{
				name: "Deoghar",
				latitude: 24.4858,
				longitude: 86.6953,
			},
		],
		districts: [
			"Bokaro",
			"Chatra",
			"Deoghar",
			"Dhanbad",
			"Dumka",
			"East Singhbhum (Jamshedpur)",
			"Garhwa",
			"Giridih",
			"Godda",
			"Gumla",
			"Hazaribagh",
			"Jamtara",
			"Khunti",
			"Koderma",
			"Latehar",
			"Lohardaga",
			"Pakur",
			"Palamu",
			"Ramgarh",
			"Ranchi",
			"Sahebganj",
			"Seraikela Kharsawan",
			"Simdega",
			"West Singhbhum (Chaibasa)",
		],
	},
	{
		name: "Karnataka",
		type: "State",
		latitude: 15.3173,
		longitude: 75.7139,
		capital: {
			name: "Bengaluru",
			latitude: 12.9716,
			longitude: 77.5946,
		},
		largestCity: {
			name: "Bengaluru",
			latitude: 12.9716,
			longitude: 77.5946,
		},
		region: "South",
		population: 61095297,
		area: 191791,
		officialLanguages: ["Kannada"],
		formationDate: "1 November 1956; renamed 1973",
		majorCities: [
			{
				name: "Bengaluru",
				latitude: 12.9716,
				longitude: 77.5946,
			},
			{
				name: "Mysuru",
				latitude: 12.2958,
				longitude: 76.6394,
			},
			{
				name: "Hubballi-Dharwad",
				latitude: 15.3647,
				longitude: 75.1239,
			},
			{
				name: "Mangaluru",
				latitude: 12.9141,
				longitude: 74.856,
			},
			{
				name: "Belagavi",
				latitude: 15.8497,
				longitude: 74.4977,
			},
		],
		districts: [
			"Bagalkot",
			"Ballari",
			"Belagavi",
			"Bengaluru Rural",
			"Bengaluru Urban",
			"Bidar",
			"Chamarajanagar",
			"Chikballapur",
			"Chikkamagaluru",
			"Chitradurga",
			"Dakshina Kannada",
			"Davangere",
			"Dharwad",
			"Gadag",
			"Hassan",
			"Haveri",
			"Kalaburagi",
			"Kodagu",
			"Kolar",
			"Koppal",
			"Mandya",
			"Raichur",
			"Ramanagara",
			"Shivamogga",
			"Tumakuru",
			"Udupi",
			"Uttara Kannada",
			"Vijayanagara",
			"Vijayapura",
			"Yadgir",
		],
	},
	{
		name: "Kerala",
		type: "State",
		latitude: 10.8505,
		longitude: 76.2711,
		capital: {
			name: "Thiruvananthapuram",
			latitude: 8.5241,
			longitude: 76.9366,
		},
		largestCity: {
			name: "Thiruvananthapuram",
			latitude: 8.5241,
			longitude: 76.9366,
		},
		region: "South",
		population: 33406061,
		area: 38852,
		officialLanguages: ["Malayalam", "English (additional)"],
		formationDate: "1 November 1956",
		majorCities: [
			{
				name: "Thiruvananthapuram",
				latitude: 8.5241,
				longitude: 76.9366,
			},
			{
				name: "Kochi",
				latitude: 9.9312,
				longitude: 76.2673,
			},
			{
				name: "Kozhikode",
				latitude: 11.2588,
				longitude: 75.7804,
			},
			{
				name: "Kollam",
				latitude: 8.8932,
				longitude: 76.6141,
			},
			{
				name: "Thrissur",
				latitude: 10.5276,
				longitude: 76.2144,
			},
		],
		districts: [
			"Alappuzha",
			"Ernakulam",
			"Idukki",
			"Kannur",
			"Kasaragod",
			"Kollam",
			"Kottayam",
			"Kozhikode",
			"Malappuram",
			"Palakkad",
			"Pathanamthitta",
			"Thiruvananthapuram",
			"Thrissur",
			"Wayanad",
		],
	},
	{
		name: "Madhya Pradesh",
		type: "State",
		latitude: 22.9734,
		longitude: 78.6569,
		capital: {
			name: "Bhopal",
			latitude: 23.2599,
			longitude: 77.4126,
		},
		largestCity: {
			name: "Indore",
			latitude: 22.7196,
			longitude: 75.8577,
		},
		region: "Central",
		population: 72626809,
		area: 308245,
		officialLanguages: ["Hindi"],
		formationDate: "1 November 1956",
		majorCities: [
			{
				name: "Indore",
				latitude: 22.7196,
				longitude: 75.8577,
			},
			{
				name: "Bhopal",
				latitude: 23.2599,
				longitude: 77.4126,
			},
			{
				name: "Jabalpur",
				latitude: 23.1815,
				longitude: 79.9864,
			},
			{
				name: "Gwalior",
				latitude: 26.2183,
				longitude: 78.1828,
			},
			{
				name: "Ujjain",
				latitude: 23.1793,
				longitude: 75.7849,
			},
		],
		districts: [
			"Agar Malwa",
			"Alirajpur",
			"Anuppur",
			"Ashoknagar",
			"Balaghat",
			"Barwani",
			"Betul",
			"Bhind",
			"Bhopal",
			"Burhanpur",
			"Chhatarpur",
			"Chhindwara",
			"Damoh",
			"Datia",
			"Dewas",
			"Dhar",
			"Dindori",
			"Guna",
			"Gwalior",
			"Harda",
			"Hoshangabad (Narmadapuram)",
			"Indore",
			"Jabalpur",
			"Jhabua",
			"Katni",
			"Khandwa (East Nimar)",
			"Khargone (West Nimar)",
			"Mandla",
			"Mandsaur",
			"Morena",
			"Narsinghpur",
			"Neemuch",
			"Niwari",
			"Panna",
			"Raisen",
			"Rajgarh",
			"Ratlam",
			"Rewa",
			"Sagar",
			"Satna",
			"Sehore",
			"Seoni",
			"Shahdol",
			"Shajapur",
			"Sheopur",
			"Shivpuri",
			"Sidhi",
			"Singrauli",
			"Tikamgarh",
			"Ujjain",
			"Umaria",
			"Vidisha",
		],
	},
	{
		name: "Maharashtra",
		type: "State",
		latitude: 19.7515,
		longitude: 75.7139,
		capital: {
			name: "Mumbai",
			latitude: 19.076,
			longitude: 72.8777,
		},
		largestCity: {
			name: "Mumbai",
			latitude: 19.076,
			longitude: 72.8777,
		},
		region: "West",
		population: 112374333,
		area: 307713,
		officialLanguages: ["Marathi"],
		formationDate: "1 May 1960",
		majorCities: [
			{
				name: "Mumbai",
				latitude: 19.076,
				longitude: 72.8777,
			},
			{
				name: "Pune",
				latitude: 18.5204,
				longitude: 73.8567,
			},
			{
				name: "Nagpur",
				latitude: 21.1458,
				longitude: 79.0882,
			},
			{
				name: "Thane",
				latitude: 19.2183,
				longitude: 72.9781,
			},
			{
				name: "Nashik",
				latitude: 19.9975,
				longitude: 73.7898,
			},
		],
		districts: [
			"Ahmednagar",
			"Akola",
			"Amravati",
			"Aurangabad",
			"Beed",
			"Bhandara",
			"Buldhana",
			"Chandrapur",
			"Dhule",
			"Gadchiroli",
			"Gondia",
			"Hingoli",
			"Jalgaon",
			"Jalna",
			"Kolhapur",
			"Latur",
			"Mumbai City",
			"Mumbai Suburban",
			"Nagpur",
			"Nanded",
			"Nandurbar",
			"Nashik",
			"Osmanabad",
			"Palghar",
			"Parbhani",
			"Pune",
			"Raigad",
			"Ratnagiri",
			"Sangli",
			"Satara",
			"Sindhudurg",
			"Solapur",
			"Thane",
			"Wardha",
			"Washim",
			"Yavatmal",
		],
	},
	{
		name: "Manipur",
		type: "State",
		latitude: 24.6637,
		longitude: 93.9063,
		capital: {
			name: "Imphal",
			latitude: 24.817,
			longitude: 93.9368,
		},
		largestCity: {
			name: "Imphal",
			latitude: 24.817,
			longitude: 93.9368,
		},
		region: "Northeast",
		population: 2855794,
		area: 22327,
		officialLanguages: ["Meitei (Manipuri)"],
		formationDate: "21 January 1972",
		majorCities: [
			{
				name: "Imphal",
				latitude: 24.817,
				longitude: 93.9368,
			},
			{
				name: "Thoubal",
				latitude: 24.6267,
				longitude: 94.0006,
			},
			{
				name: "Bishnupur",
				latitude: 24.6287,
				longitude: 93.7519,
			},
			{
				name: "Churachandpur",
				latitude: 24.3334,
				longitude: 93.6733,
			},
		],
		districts: [
			"Bishnupur",
			"Chandel",
			"Churachandpur",
			"Imphal East",
			"Imphal West",
			"Jiribam",
			"Kakching",
			"Kamjong",
			"Kangpokpi",
			"Noney",
			"Pherzawl",
			"Senapati",
			"Tamenglong",
			"Tengnoupal",
			"Thoubal",
			"Ukhrul",
		],
	},
	{
		name: "Meghalaya",
		type: "State",
		latitude: 25.467,
		longitude: 91.3662,
		capital: {
			name: "Shillong",
			latitude: 25.5788,
			longitude: 91.8933,
		},
		largestCity: {
			name: "Shillong",
			latitude: 25.5788,
			longitude: 91.8933,
		},
		region: "Northeast",
		population: 2966889,
		area: 22429,
		officialLanguages: ["English"],
		formationDate: "21 January 1972",
		majorCities: [
			{
				name: "Shillong",
				latitude: 25.5788,
				longitude: 91.8933,
			},
			{
				name: "Tura",
				latitude: 25.514,
				longitude: 90.2035,
			},
			{
				name: "Jowai",
				latitude: 25.4499,
				longitude: 92.2022,
			},
			{
				name: "Nongstoin",
				latitude: 25.5171,
				longitude: 91.2642,
			},
		],
		districts: [
			"East Garo Hills",
			"East Jaintia Hills",
			"East Khasi Hills",
			"North Garo Hills",
			"Ri Bhoi",
			"South Garo Hills",
			"South West Garo Hills",
			"South West Khasi Hills",
			"West Garo Hills",
			"West Jaintia Hills",
			"West Khasi Hills",
		],
	},
	{
		name: "Mizoram",
		type: "State",
		latitude: 23.1645,
		longitude: 92.9376,
		capital: {
			name: "Aizawl",
			latitude: 23.7271,
			longitude: 92.7173,
		},
		largestCity: {
			name: "Aizawl",
			latitude: 23.7271,
			longitude: 92.7173,
		},
		region: "Northeast",
		population: 1097206,
		area: 21081,
		officialLanguages: ["Mizo", "English", "Hindi"],
		formationDate: "20 February 1987",
		majorCities: [
			{
				name: "Aizawl",
				latitude: 23.7271,
				longitude: 92.7173,
			},
			{
				name: "Lunglei",
				latitude: 22.8673,
				longitude: 92.7624,
			},
			{
				name: "Saiha",
				latitude: 22.4918,
				longitude: 92.9771,
			},
			{
				name: "Champhai",
				latitude: 23.457,
				longitude: 93.328,
			},
		],
		districts: [
			"Aizawl",
			"Champhai",
			"Kolasib",
			"Lawngtlai",
			"Lunglei",
			"Mamit",
			"Saiha",
			"Serchhip",
			"Hnahthial",
			"Khawzawl",
			"Saitual",
		],
	},
	{
		name: "Nagaland",
		type: "State",
		latitude: 26.1584,
		longitude: 94.5624,
		capital: {
			name: "Kohima",
			latitude: 25.6751,
			longitude: 94.1086,
		},
		largestCity: {
			name: "Dimapur",
			latitude: 25.9063,
			longitude: 93.7276,
		},
		region: "Northeast",
		population: 1978502,
		area: 16579,
		officialLanguages: ["English"],
		formationDate: "1 December 1963",
		majorCities: [
			{
				name: "Dimapur",
				latitude: 25.9063,
				longitude: 93.7276,
			},
			{
				name: "Kohima",
				latitude: 25.6751,
				longitude: 94.1086,
			},
			{
				name: "Mokokchung",
				latitude: 26.3247,
				longitude: 94.5288,
			},
			{
				name: "Tuensang",
				latitude: 26.2676,
				longitude: 94.8234,
			},
		],
		districts: [
			"Chümoukedima",
			"Dimapur",
			"Kiphire",
			"Kohima",
			"Longleng",
			"Mokokchung",
			"Mon",
			"Niuland",
			"Noklak",
			"Peren",
			"Phek",
			"Tseminyü",
			"Tuensang",
			"Wokha",
			"Zünheboto",
		],
	},
	{
		name: "Odisha",
		type: "State",
		latitude: 20.9517,
		longitude: 85.0985,
		capital: {
			name: "Bhubaneswar",
			latitude: 20.2961,
			longitude: 85.8245,
		},
		largestCity: {
			name: "Bhubaneswar",
			latitude: 20.2961,
			longitude: 85.8245,
		},
		region: "East",
		population: 41974218,
		area: 155707,
		officialLanguages: ["Odia"],
		formationDate: "1 April 1936; 26 January 1950 (state)",
		majorCities: [
			{
				name: "Bhubaneswar",
				latitude: 20.2961,
				longitude: 85.8245,
			},
			{
				name: "Cuttack",
				latitude: 20.4625,
				longitude: 85.883,
			},
			{
				name: "Rourkela",
				latitude: 22.2604,
				longitude: 84.8536,
			},
			{
				name: "Berhampur",
				latitude: 19.3114,
				longitude: 84.7929,
			},
			{
				name: "Sambalpur",
				latitude: 21.4669,
				longitude: 83.9812,
			},
		],
		districts: [
			"Angul",
			"Balangir",
			"Balasore (Baleswar)",
			"Bargarh",
			"Bhadrak",
			"Boudh",
			"Cuttack",
			"Deogarh (Debagarh)",
			"Dhenkanal",
			"Gajapati",
			"Ganjam",
			"Jagatsinghpur",
			"Jajpur",
			"Jharsuguda",
			"Kalahandi",
			"Kandhamal",
			"Kendrapara",
			"Kendujhar (Keonjhar)",
			"Khordha",
			"Koraput",
			"Malkangiri",
			"Mayurbhanj",
			"Nabarangpur",
			"Nayagarh",
			"Nuapada",
			"Puri",
			"Rayagada",
			"Sambalpur",
			"Subarnapur (Sonepur)",
			"Sundargarh",
		],
	},
	{
		name: "Punjab",
		type: "State",
		latitude: 31.1471,
		longitude: 75.3412,
		capital: {
			name: "Chandigarh",
			latitude: 30.7333,
			longitude: 76.7794,
		},
		largestCity: {
			name: "Ludhiana",
			latitude: 30.9009,
			longitude: 75.8573,
		},
		region: "North",
		population: 27743338,
		area: 50362,
		officialLanguages: ["Punjabi"],
		formationDate: "1 November 1956; 1 November 1966 (Haryana carved out)",
		majorCities: [
			{
				name: "Ludhiana",
				latitude: 30.9009,
				longitude: 75.8573,
			},
			{
				name: "Amritsar",
				latitude: 31.634,
				longitude: 74.8723,
			},
			{
				name: "Jalandhar",
				latitude: 31.326,
				longitude: 75.5762,
			},
			{
				name: "Patiala",
				latitude: 30.3398,
				longitude: 76.3869,
			},
			{
				name: "Bathinda",
				latitude: 30.21,
				longitude: 74.9455,
			},
		],
		districts: [
			"Amritsar",
			"Barnala",
			"Bathinda",
			"Faridkot",
			"Fatehgarh Sahib",
			"Fazilka",
			"Ferozepur",
			"Gurdaspur",
			"Hoshiarpur",
			"Jalandhar",
			"Kapurthala",
			"Ludhiana",
			"Mansa",
			"Moga",
			"Mohali (SAS Nagar)",
			"Muktsar",
			"Nawanshahr (Shahid Bhagat Singh Nagar)",
			"Pathankot",
			"Patiala",
			"Rupnagar",
			"Sangrur",
			"Tarn Taran",
			"Malerkotla",
		],
	},
	{
		name: "Rajasthan",
		type: "State",
		latitude: 27.0238,
		longitude: 74.2179,
		capital: {
			name: "Jaipur",
			latitude: 26.9124,
			longitude: 75.7873,
		},
		largestCity: {
			name: "Jaipur",
			latitude: 26.9124,
			longitude: 75.7873,
		},
		region: "North",
		population: 68548437,
		area: 342239,
		officialLanguages: ["Hindi", "Rajasthani (spoken)"],
		formationDate: "30 March 1949",
		majorCities: [
			{
				name: "Jaipur",
				latitude: 26.9124,
				longitude: 75.7873,
			},
			{
				name: "Jodhpur",
				latitude: 26.2389,
				longitude: 73.0243,
			},
			{
				name: "Kota",
				latitude: 25.2138,
				longitude: 75.8648,
			},
			{
				name: "Bikaner",
				latitude: 28.0229,
				longitude: 73.3119,
			},
			{
				name: "Udaipur",
				latitude: 24.5854,
				longitude: 73.7125,
			},
		],
		districts: [
			"Ajmer",
			"Alwar",
			"Banswara",
			"Baran",
			"Barmer",
			"Bharatpur",
			"Bhilwara",
			"Bikaner",
			"Bundi",
			"Chittorgarh",
			"Churu",
			"Dausa",
			"Dholpur",
			"Dungarpur",
			"Hanumangarh",
			"Jaipur",
			"Jaisalmer",
			"Jalore",
			"Jhalawar",
			"Jhunjhunu",
			"Jodhpur",
			"Karauli",
			"Kota",
			"Nagaur",
			"Pali",
			"Pratapgarh",
			"Rajsamand",
			"Sawai Madhopur",
			"Sikar",
			"Sirohi",
			"Sri Ganganagar",
			"Tonk",
			"Udaipur",
		],
	},
	{
		name: "Sikkim",
		type: "State",
		latitude: 27.533,
		longitude: 88.5122,
		capital: {
			name: "Gangtok",
			latitude: 27.3389,
			longitude: 88.6065,
		},
		largestCity: {
			name: "Gangtok",
			latitude: 27.3389,
			longitude: 88.6065,
		},
		region: "Northeast",
		population: 610577,
		area: 7096,
		officialLanguages: ["English", "Nepali", "Lepcha", "Bhutia", "Limbu"],
		formationDate: "16 May 1975",
		majorCities: [
			{
				name: "Gangtok",
				latitude: 27.3389,
				longitude: 88.6065,
			},
			{
				name: "Geyzing",
				latitude: 27.2891,
				longitude: 88.2641,
			},
			{
				name: "Namchi",
				latitude: 27.1657,
				longitude: 88.3953,
			},
			{
				name: "Mangan",
				latitude: 27.5167,
				longitude: 88.5302,
			},
		],
		districts: [
			"Gangtok",
			"Gyalshing",
			"Mangan",
			"Namchi",
			"Nandugaon",
			"Pakyong",
			"Soreng",
		],
	},
	{
		name: "Tamil Nadu",
		type: "State",
		latitude: 11.1271,
		longitude: 78.6569,
		capital: {
			name: "Chennai",
			latitude: 13.0827,
			longitude: 80.2707,
		},
		largestCity: {
			name: "Chennai",
			latitude: 13.0827,
			longitude: 80.2707,
		},
		region: "South",
		population: 72147030,
		area: 130058,
		officialLanguages: ["Tamil"],
		formationDate: "1 November 1956 (as Madras State); renamed 1969",
		majorCities: [
			{
				name: "Chennai",
				latitude: 13.0827,
				longitude: 80.2707,
			},
			{
				name: "Coimbatore",
				latitude: 11.0168,
				longitude: 76.9558,
			},
			{
				name: "Madurai",
				latitude: 9.9252,
				longitude: 78.1198,
			},
			{
				name: "Tiruchirappalli",
				latitude: 10.7905,
				longitude: 78.7047,
			},
			{
				name: "Salem",
				latitude: 11.6643,
				longitude: 78.146,
			},
		],
		districts: [
			"Ariyalur",
			"Chengalpattu",
			"Chennai",
			"Coimbatore",
			"Cuddalore",
			"Dharmapuri",
			"Dindigul",
			"Erode",
			"Kallakurichi",
			"Kanchipuram",
			"Kanyakumari",
			"Karur",
			"Krishnagiri",
			"Madurai",
			"Mayiladuthurai",
			"Nagapattinam",
			"Namakkal",
			"Nilgiris",
			"Perambalur",
			"Pudukkottai",
			"Ramanathapuram",
			"Ranipet",
			"Salem",
			"Sivaganga",
			"Tenkasi",
			"Thanjavur",
			"Theni",
			"Thoothukudi (Tuticorin)",
			"Tiruchirappalli",
			"Tirunelveli",
			"Tirupathur",
			"Tiruppur",
			"Tiruvallur",
			"Tiruvannamalai",
			"Tiruvarur",
			"Vellore",
			"Viluppuram",
			"Virudhunagar",
		],
	},
	{
		name: "Telangana",
		type: "State",
		latitude: 18.1124,
		longitude: 79.0193,
		capital: {
			name: "Hyderabad",
			latitude: 17.385,
			longitude: 78.4867,
		},
		largestCity: {
			name: "Hyderabad",
			latitude: 17.385,
			longitude: 78.4867,
		},
		region: "South",
		population: 35286757,
		area: 112077,
		officialLanguages: ["Telugu", "Urdu"],
		formationDate: "2 June 2014",
		majorCities: [
			{
				name: "Hyderabad",
				latitude: 17.385,
				longitude: 78.4867,
			},
			{
				name: "Warangal",
				latitude: 17.9689,
				longitude: 79.5941,
			},
			{
				name: "Nizamabad",
				latitude: 18.6739,
				longitude: 78.1,
			},
			{
				name: "Khammam",
				latitude: 17.2473,
				longitude: 80.1437,
			},
			{
				name: "Karimnagar",
				latitude: 18.4386,
				longitude: 79.1288,
			},
		],
		districts: [
			"Adilabad",
			"Bhadradri Kothagudem",
			"Hanamkonda",
			"Hyderabad",
			"Jagitial",
			"Jangaon",
			"Jayashankar Bhupalpally",
			"Jogulamba Gadwal",
			"Kamareddy",
			"Karimnagar",
			"Khammam",
			"Kumuram Bheem Asifabad",
			"Mahabubabad",
			"Mahabubnagar",
			"Mancherial",
			"Medak",
			"Medchal–Malkajgiri",
			"Mulugu",
			"Nagarkurnool",
			"Nalgonda",
			"Narayanpet",
			"Nirmal",
			"Nizamabad",
			"Peddapalli",
			"Rajanna Sircilla",
			"Rangareddy",
			"Sangareddy",
			"Siddipet",
			"Suryapet",
			"Vikarabad",
			"Wanaparthy",
			"Warangal",
			"Yadadri Bhuvanagiri",
		],
	},
	{
		name: "Tripura",
		type: "State",
		latitude: 23.9408,
		longitude: 91.9882,
		capital: {
			name: "Agartala",
			latitude: 23.8315,
			longitude: 91.2868,
		},
		largestCity: {
			name: "Agartala",
			latitude: 23.8315,
			longitude: 91.2868,
		},
		region: "Northeast",
		population: 3673917,
		area: 10486,
		officialLanguages: ["Bengali", "Kokborok", "English"],
		formationDate: "21 January 1972",
		majorCities: [
			{
				name: "Agartala",
				latitude: 23.8315,
				longitude: 91.2868,
			},
			{
				name: "Udaipur",
				latitude: 23.5354,
				longitude: 91.4998,
			},
			{
				name: "Dharmanagar",
				latitude: 24.3639,
				longitude: 92.1717,
			},
			{
				name: "Kailasahar",
				latitude: 24.328,
				longitude: 92.0049,
			},
		],
		districts: [
			"Dhalai",
			"Gomati",
			"Khowai",
			"North Tripura",
			"Sepahijala",
			"South Tripura",
			"Unakoti",
			"West Tripura",
		],
	},
	{
		name: "Uttar Pradesh",
		type: "State",
		latitude: 26.8467,
		longitude: 80.9462,
		capital: {
			name: "Lucknow",
			latitude: 26.8467,
			longitude: 80.9462,
		},
		largestCity: {
			name: "Kanpur",
			latitude: 26.4499,
			longitude: 80.3319,
		},
		region: "North",
		population: 199812341,
		area: 240928,
		officialLanguages: ["Hindi", "Urdu"],
		formationDate: "1 April 1937; renamed 24 January 1950",
		majorCities: [
			{
				name: "Lucknow",
				latitude: 26.8467,
				longitude: 80.9462,
			},
			{
				name: "Kanpur",
				latitude: 26.4499,
				longitude: 80.3319,
			},
			{
				name: "Ghaziabad",
				latitude: 28.6692,
				longitude: 77.4538,
			},
			{
				name: "Agra",
				latitude: 27.1767,
				longitude: 78.0081,
			},
			{
				name: "Varanasi",
				latitude: 25.3176,
				longitude: 82.9739,
			},
		],
		districts: [
			"Agra",
			"Aligarh",
			"Ambedkar Nagar",
			"Amethi",
			"Amroha (J.P. Nagar)",
			"Auraiya",
			"Ayodhya (Faizabad)",
			"Azamgarh",
			"Badaun",
			"Baghpat",
			"Bahraich",
			"Ballia",
			"Balrampur",
			"Banda",
			"Barabanki",
			"Bareilly",
			"Basti",
			"Bijnor",
			"Bulandshahr",
			"Chandauli",
			"Chitrakoot",
			"Deoria",
			"Etah",
			"Etawah",
			"Farrukhabad",
			"Fatehpur",
			"Firozabad",
			"Gautam Buddh Nagar",
			"Ghaziabad",
			"Ghazipur",
			"Gonda",
			"Gorakhpur",
			"Hamirpur",
			"Hapur (Panchsheel Nagar)",
			"Hardoi",
			"Hathras (Mahamaya Nagar)",
			"Jalaun",
			"Jaunpur",
			"Jhansi",
			"Kannauj",
			"Kanpur Dehat",
			"Kanpur Nagar",
			"Kasganj",
			"Kaushambi",
			"Kushinagar (Padrauna)",
			"Lakhimpur Kheri",
			"Lalitpur",
			"Lucknow",
			"Maharajganj",
			"Mahoba",
			"Mainpuri",
			"Mathura",
			"Mau",
			"Meerut",
			"Mirzapur",
			"Moradabad",
			"Muzaffarnagar",
			"Pilibhit",
			"Pratapgarh",
			"Prayagraj (Allahabad)",
			"Rae Bareli",
			"Rampur",
			"Saharanpur",
			"Sambhal (Bhim Nagar)",
			"Sant Kabir Nagar",
			"Sant Ravidas Nagar (Bhadohi)",
			"Shahjahanpur",
			"Shamli (Prabuddh Nagar)",
			"Shrawasti",
			"Siddharthnagar",
			"Sitapur",
			"Sonbhadra",
			"Sultanpur",
			"Unnao",
			"Varanasi",
		],
	},
	{
		name: "Uttarakhand",
		type: "State",
		latitude: 30.0668,
		longitude: 79.0193,
		capital: [
			{
				name: "Gairsain (summer)",
				latitude: 30.0534,
				longitude: 79.2961,
			},
			{
				name: "Dehradun (winter)",
				latitude: 30.3165,
				longitude: 78.0322,
			},
		],
		largestCity: {
			name: "Dehradun",
			latitude: 30.3165,
			longitude: 78.0322,
		},
		region: "North",
		population: 10086292,
		area: 53483,
		officialLanguages: ["Hindi", "Sanskrit"],
		formationDate: "9 November 2000",
		majorCities: [
			{
				name: "Dehradun",
				latitude: 30.3165,
				longitude: 78.0322,
			},
			{
				name: "Haridwar",
				latitude: 29.9457,
				longitude: 78.1642,
			},
			{
				name: "Haldwani",
				latitude: 29.219,
				longitude: 79.5121,
			},
			{
				name: "Roorkee",
				latitude: 29.8543,
				longitude: 77.888,
			},
			{
				name: "Rudrapur",
				latitude: 28.977,
				longitude: 79.3995,
			},
		],
		districts: [
			"Almora",
			"Bageshwar",
			"Chamoli",
			"Champawat",
			"Dehradun",
			"Haridwar",
			"Nainital",
			"Pauri Garhwal",
			"Pithoragarh",
			"Rudraprayag",
			"Tehri Garhwal",
			"Udham Singh Nagar",
			"Uttarkashi",
		],
	},
	{
		name: "West Bengal",
		type: "State",
		latitude: 22.9868,
		longitude: 87.855,
		capital: {
			name: "Kolkata",
			latitude: 22.5726,
			longitude: 88.3639,
		},
		largestCity: {
			name: "Kolkata",
			latitude: 22.5726,
			longitude: 88.3639,
		},
		region: "East",
		population: 91276115,
		area: 88752,
		officialLanguages: ["Bengali", "English"],
		formationDate: "1 November 1956",
		majorCities: [
			{
				name: "Kolkata",
				latitude: 22.5726,
				longitude: 88.3639,
			},
			{
				name: "Howrah",
				latitude: 22.5958,
				longitude: 88.2636,
			},
			{
				name: "Siliguri",
				latitude: 26.7271,
				longitude: 88.3953,
			},
			{
				name: "Asansol",
				latitude: 23.685,
				longitude: 86.9524,
			},
			{
				name: "Durgapur",
				latitude: 23.5204,
				longitude: 87.3119,
			},
		],
		districts: [
			"Alipurduar",
			"Bankura",
			"Birbhum",
			"Cooch Behar",
			"Dakshin Dinajpur (South Dinajpur)",
			"Darjeeling",
			"Hooghly",
			"Howrah",
			"Jalpaiguri",
			"Jhargram",
			"Kalimpong",
			"Kolkata",
			"Malda",
			"Murshidabad",
			"Nadia",
			"North 24 Parganas",
			"Paschim Bardhaman",
			"Paschim Medinipur",
			"Purba Bardhaman",
			"Purba Medinipur",
			"Purulia",
			"South 24 Parganas",
			"Uttar Dinajpur (North Dinajpur)",
		],
	},
	{
		name: "Andaman and Nicobar Islands",
		type: "Union Territory",
		latitude: 11.7401,
		longitude: 92.6586,
		capital: {
			name: "Port Blair",
			latitude: 11.6234,
			longitude: 92.7265,
		},
		largestCity: {
			name: "Port Blair",
			latitude: 11.6234,
			longitude: 92.7265,
		},
		region: "Bay of Bengal",
		population: 380581,
		area: 8249,
		officialLanguages: ["Hindi", "English"],
		formationDate: "1 November 1956",
		majorCities: [
			{
				name: "Port Blair",
				latitude: 11.6234,
				longitude: 92.7265,
			},
		],
		districts: ["Nicobar", "North and Middle Andaman", "South Andaman"],
	},
	{
		name: "Chandigarh",
		type: "Union Territory",
		latitude: 30.7333,
		longitude: 76.7794,
		capital: {
			name: "Chandigarh",
			latitude: 30.7333,
			longitude: 76.7794,
		},
		largestCity: {
			name: "Chandigarh",
			latitude: 30.7333,
			longitude: 76.7794,
		},
		region: "North",
		population: 1055450,
		area: 114,
		officialLanguages: ["English", "Hindi", "Punjabi"],
		formationDate: "1 November 1966",
		majorCities: [
			{
				name: "Chandigarh",
				latitude: 30.7333,
				longitude: 76.7794,
			},
		],
		districts: ["Chandigarh"],
	},
	{
		name: "Dadra & Nagar Haveli and Daman & Diu",
		type: "Union Territory",
		latitude: 20.4283,
		longitude: 72.8397,
		capital: {
			name: "Daman",
			latitude: 20.3974,
			longitude: 72.8328,
		},
		largestCity: {
			name: "Silvassa",
			latitude: 20.273,
			longitude: 73.0139,
		},
		region: "West",
		population: 585764,
		area: 603,
		officialLanguages: ["Gujarati", "Hindi", "English"],
		formationDate: "26 January 2020 (merger)",
		majorCities: [
			{
				name: "Silvassa",
				latitude: 20.273,
				longitude: 73.0139,
			},
			{
				name: "Daman",
				latitude: 20.3974,
				longitude: 72.8328,
			},
			{
				name: "Diu",
				latitude: 20.7146,
				longitude: 70.987,
			},
		],
		districts: ["Dadra & Nagar Haveli", "Daman", "Diu"],
	},
	{
		name: "Delhi (NCT)",
		type: "Union Territory with Legislature",
		latitude: 28.7041,
		longitude: 77.1025,
		capital: {
			name: "New Delhi",
			latitude: 28.6139,
			longitude: 77.209,
		},
		largestCity: {
			name: "Delhi",
			latitude: 28.7041,
			longitude: 77.1025,
		},
		region: "North",
		population: 16753235,
		area: 1484,
		officialLanguages: ["Hindi", "English", "Punjabi", "Urdu"],
		formationDate: "1956 (UT); 1 February 1992 (NCT)",
		majorCities: [
			{
				name: "Delhi",
				latitude: 28.7041,
				longitude: 77.1025,
			},
			{
				name: "New Delhi",
				latitude: 28.6139,
				longitude: 77.209,
			},
		],
		districts: [
			"Central Delhi",
			"East Delhi",
			"New Delhi",
			"North Delhi",
			"North East Delhi",
			"North West Delhi",
			"Shahdara",
			"South Delhi",
			"South East Delhi",
			"South West Delhi",
			"West Delhi",
		],
	},
	{
		name: "Jammu and Kashmir",
		type: "Union Territory",
		latitude: 33.2778,
		longitude: 75.3412,
		capital: [
			{
				name: "Srinagar (summer)",
				latitude: 34.0837,
				longitude: 74.7973,
			},
			{
				name: "Jammu (winter)",
				latitude: 32.7266,
				longitude: 74.857,
			},
		],
		largestCity: {
			name: "Srinagar",
			latitude: 34.0837,
			longitude: 74.7973,
		},
		region: "North",
		population: 12267032,
		area: 42241,
		officialLanguages: ["Kashmiri", "Dogri", "Hindi", "English", "Urdu"],
		formationDate: "31 October 2019",
		majorCities: [
			{
				name: "Srinagar",
				latitude: 34.0837,
				longitude: 74.7973,
			},
			{
				name: "Jammu",
				latitude: 32.7266,
				longitude: 74.857,
			},
			{
				name: "Anantnag",
				latitude: 33.7294,
				longitude: 75.1544,
			},
			{
				name: "Baramulla",
				latitude: 34.1988,
				longitude: 74.3637,
			},
			{
				name: "Udhampur",
				latitude: 32.924,
				longitude: 75.1357,
			},
		],
		districts: [
			"Anantnag",
			"Bandipora",
			"Baramulla",
			"Budgam",
			"Doda",
			"Ganderbal",
			"Jammu",
			"Kathua",
			"Kishtwar",
			"Kulgam",
			"Kupwara",
			"Poonch",
			"Pulwama",
			"Rajouri",
			"Ramban",
			"Reasi",
			"Samba",
			"Shopian",
			"Srinagar",
			"Udhampur",
		],
	},
	{
		name: "Ladakh",
		type: "Union Territory",
		latitude: 34.2268,
		longitude: 77.5619,
		capital: [
			{
				name: "Leh",
				latitude: 34.1526,
				longitude: 77.5771,
			},
			{
				name: "Kargil (proposed)",
				latitude: 34.5553,
				longitude: 76.132,
			},
		],
		largestCity: {
			name: "Leh",
			latitude: 34.1526,
			longitude: 77.5771,
		},
		region: "North",
		population: 274289,
		area: 59146,
		officialLanguages: ["Hindi", "English"],
		formationDate: "31 October 2019",
		majorCities: [
			{
				name: "Leh",
				latitude: 34.1526,
				longitude: 77.5771,
			},
			{
				name: "Kargil",
				latitude: 34.5553,
				longitude: 76.132,
			},
		],
		districts: ["Kargil", "Leh"],
	},
	{
		name: "Lakshadweep",
		type: "Union Territory",
		latitude: 10.328,
		longitude: 72.7846,
		capital: {
			name: "Kavaratti",
			latitude: 10.5593,
			longitude: 72.6358,
		},
		largestCity: {
			name: "Kavaratti",
			latitude: 10.5593,
			longitude: 72.6358,
		},
		region: "Arabian Sea",
		population: 64429,
		area: 32,
		officialLanguages: ["Malayalam", "English"],
		formationDate: "1 November 1956",
		majorCities: [
			{
				name: "Kavaratti",
				latitude: 10.5593,
				longitude: 72.6358,
			},
			{
				name: "Agatti",
				latitude: 10.8553,
				longitude: 72.1959,
			},
			{
				name: "Amini",
				latitude: 11.1085,
				longitude: 72.7333,
			},
		],
		districts: ["Lakshadweep"],
	},
	{
		name: "Puducherry (Pondicherry)",
		type: "Union Territory",
		latitude: 11.9416,
		longitude: 79.8083,
		capital: {
			name: "Puducherry",
			latitude: 11.9139,
			longitude: 79.8145,
		},
		largestCity: {
			name: "Puducherry",
			latitude: 11.9139,
			longitude: 79.8145,
		},
		region: "South",
		population: 1247953,
		area: 479,
		officialLanguages: ["Tamil", "French", "Malayalam", "Telugu", "English"],
		formationDate: "1 November 1954 (de facto), 16 August 1962 (de jure)",
		majorCities: [
			{
				name: "Puducherry",
				latitude: 11.9139,
				longitude: 79.8145,
			},
			{
				name: "Oulgaret",
				latitude: 11.9564,
				longitude: 79.7852,
			},
			{
				name: "Karaikal",
				latitude: 10.9254,
				longitude: 79.838,
			},
			{
				name: "Yanam",
				latitude: 16.7339,
				longitude: 82.2133,
			},
			{
				name: "Mahe",
				latitude: 11.7017,
				longitude: 75.534,
			},
		],
		districts: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
	},
];
