/** @format */

export const SIDEBAR_OPEN2 = "SIDEBAR_OPEN2";
export const SIDEBAR_CLOSE2 = "SIDEBAR_CLOSE2";
export const LANGUAGE_TOGGLE = "LANGUAGE_TOGGLE";
export const CHOSEN_LANGUAGE = "CHOSEN_LANGUAGE";
export const SET_WEBSITE_SETUP = "SET_WEBSITE_SETUP";
export const FEATURED_PROPERTIES = "FEATURED_PROPERTIES";
